version: '3.8'

services:
  my-db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: pwe1234
      MARIADB_DATABASE: commerce-system
      MARIADB_USER: user
      MARIADB_PASSWORD: pwe1234
    ports:
      - 3310:3306
    networks:
      - commerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

#  my-api-server:
#    container_name: go-server
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 3031:8080
#    networks:
#      - commerce-network
#    depends_on:
#      my-db:
#        condition: service_healthy

networks:
  commerce-network:
    driver: bridge
