services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: pwe1234
      MARIADB_DATABASE: commerce-system
      MARIADB_USER: user
      MARIADB_PASSWORD: pwe1234
    ports:
      - 3310:3306
    networks:
      - commerce-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppwe1234"]
      interval: 5s
      retries: 10
      start_period: 60s
      timeout: 5s

  api-server:
    container_name: go-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3031:3031
    networks:
      - commerce-network
    depends_on:
      - db

networks:
  commerce-network:
    driver: bridge
