services:
  my-api-server:
    container_name: go-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3031:8080
    networks:
      - commerce-network

  my-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: pwe1234
      MYSQL_DATABASE: commerce-system
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - commerce-network

networks:
  commerce-network:
    driver: bridge
