# MariaDB 설정, 컨테이너 통신용
mariadb_host = "db"
mariadb_user = "user"
mariadb_password = "pwe1234"
mariadb_db = "commerce-system"
mariadb_port = 3306

host = "localhost:3031"
scheme = "http"
version = "1.0"
basePath = "/api"
title = "commerce-system API"