# MariaDB 설정
mariadb_host = "my-db"
mariadb_user = "user"
mariadb_password = "password"
mariadb_db = "commerce-system"
mariadb_port = "3306"

# Swagger 설정
host = "localhost:3031"
scheme = "http"
version = "1.0"
basePath = "/api"
title = "commerce-system API"