definitions:
  request.CreateOrderRequest:
    properties:
      product_number:
        type: string
      quantity:
        type: integer
    type: object
  request.CreateProductRequest:
    properties:
      category:
        type: string
      price:
        type: integer
      product_name:
        type: string
      stock_quantity:
        type: integer
    type: object
  request.LoginRequest:
    properties:
      hashed_password:
        type: string
      username:
        type: string
    type: object
  request.RegisterMemberRequest:
    properties:
      email:
        type: string
      full_name:
        type: string
      is_admin:
        type: boolean
      is_withdrawn:
        type: boolean
      password:
        type: string
      username:
        type: string
    type: object
  request.UpdateMemberRequest:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
  request.UpdateStockRequest:
    properties:
      stock_quantity:
        type: integer
    type: object
  response.LoginResponse:
    properties:
      token:
        type: string
    type: object
  response.MemberResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      is_admin:
        type: boolean
      is_withdrawn:
        type: boolean
      member_number:
        type: string
      username:
        type: string
      withdrawn_at:
        type: string
    type: object
  response.MemberStatsResponse:
    properties:
      deleted_members:
        type: integer
      joined_members:
        type: integer
      month:
        type: string
    type: object
  response.OrderResponse:
    properties:
      canceled_at:
        type: string
      id:
        type: integer
      is_canceled:
        type: boolean
      member_number:
        type: string
      order_date:
        type: string
      order_number:
        type: string
      price:
        type: integer
      product_number:
        type: string
      quantity:
        type: integer
      total_amount:
        type: integer
    type: object
  response.OrderStatsResponse:
    properties:
      month:
        type: string
      total_canceled:
        type: integer
      total_sales:
        type: integer
    type: object
  response.ProductResponse:
    properties:
      category:
        type: string
      id:
        type: integer
      price:
        type: integer
      product_name:
        type: string
      product_number:
        type: string
      stock_quantity:
        type: integer
    type: object
  usecases.HealthStatus:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
  title: commerce-system API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: 서비스의 상태를 확인하고 정상 동작 여부를 검증합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 서비스 상태
          schema:
            $ref: '#/definitions/usecases.HealthStatus'
        "500":
          description: 서버 오류
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 서비스 상태 확인
      tags:
      - health
  /login:
    post:
      consumes:
      - application/json
      description: 사용자 인증 정보를 확인하고 JWT 토큰을 반환합니다.
      parameters:
      - description: 사용자 로그인 정보
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 로그인 성공
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 인증 실패
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 서버 오류
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 사용자 로그인
      tags:
      - auth
  /members:
    get:
      consumes:
      - application/json
      description: 모든 회원의 목록을 조회합니다. (관리자 전용)
      produces:
      - application/json
      responses:
        "200":
          description: 회원 목록
          schema:
            items:
              $ref: '#/definitions/response.MemberResponse'
            type: array
        "403":
          description: 권한 없음
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 목록 조회 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 회원 목록 조회
      tags:
      - members
    post:
      consumes:
      - application/json
      description: 새로운 회원을 등록합니다.
      parameters:
      - description: 회원 가입 정보
        in: body
        name: registerRequest
        required: true
        schema:
          $ref: '#/definitions/request.RegisterMemberRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 가입 성공
          schema:
            $ref: '#/definitions/response.MemberResponse'
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 서버 오류
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 회원 가입
      tags:
      - members
  /members/me:
    delete:
      consumes:
      - application/json
      description: 인증된 사용자의 계정을 삭제합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 삭제 성공
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 삭제 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 회원 탈퇴
      tags:
      - members
    get:
      consumes:
      - application/json
      description: 인증된 사용자의 정보를 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 내 정보
          schema:
            $ref: '#/definitions/response.MemberResponse'
        "500":
          description: 정보 조회 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 내 정보 조회
      tags:
      - members
    put:
      consumes:
      - application/json
      description: 인증된 사용자의 정보를 수정합니다.
      parameters:
      - description: 수정할 정보
        in: body
        name: updateRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdateMemberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 수정 성공
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 수정 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 내 정보 수정
      tags:
      - members
  /members/stats:
    get:
      consumes:
      - application/json
      description: 특정 월의 회원 가입 통계를 조회합니다. (관리자 전용)
      parameters:
      - description: 조회할 월 (YYYY-MM)
        in: query
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 통계 정보
          schema:
            $ref: '#/definitions/response.MemberStatsResponse'
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 권한 없음
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 통계 조회 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 회원 통계 조회
      tags:
      - members
  /orders:
    post:
      consumes:
      - application/json
      description: 새로운 주문을 생성합니다.
      parameters:
      - description: 주문 정보
        in: body
        name: orderRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 주문 생성 성공
          schema:
            $ref: '#/definitions/response.OrderResponse'
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 주문 생성 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 주문 생성
      tags:
      - orders
  /orders/:id/cancel:
    put:
      consumes:
      - application/json
      description: 특정 주문을 취소합니다.
      parameters:
      - description: 기본키 (primary key)
        in: path
        name: ID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 취소 성공
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 취소 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 주문 취소
      tags:
      - orders
  /orders/me:
    get:
      consumes:
      - application/json
      description: 인증된 사용자의 주문 내역을 조회합니다.
      produces:
      - application/json
      responses:
        "200":
          description: 주문 목록
          schema:
            items:
              $ref: '#/definitions/response.OrderResponse'
            type: array
        "500":
          description: 주문 조회 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 내 주문 조회
      tags:
      - orders
  /orders/stats:
    get:
      consumes:
      - application/json
      description: 특정 월의 주문 통계를 조회합니다. (관리자 전용)
      parameters:
      - description: 조회할 월 (YYYY-MM)
        in: query
        name: month
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 통계 정보
          schema:
            $ref: '#/definitions/response.OrderStatsResponse'
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 권한 없음
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 통계 조회 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 주문 통계 조회
      tags:
      - orders
  /products:
    get:
      consumes:
      - application/json
      description: 상품 목록을 필터링하여 조회합니다.
      parameters:
      - description: 카테고리
        in: query
        name: category
        type: string
      - description: 상품명
        in: query
        name: product_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 상품 목록
          schema:
            items:
              $ref: '#/definitions/response.ProductResponse'
            type: array
        "500":
          description: 조회 실패
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 상품 목록 조회
      tags:
      - products
    post:
      consumes:
      - application/json
      description: 새로운 상품을 등록합니다. (관리자 전용)
      parameters:
      - description: 상품 정보
        in: body
        name: productRequest
        required: true
        schema:
          $ref: '#/definitions/request.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: 생성 성공
          schema:
            $ref: '#/definitions/response.ProductResponse'
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 권한 없음
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 생성 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 상품 생성
      tags:
      - products
  /products/:id:
    delete:
      consumes:
      - application/json
      description: 상품을 삭제합니다. (관리자 전용)
      parameters:
      - description: 기본키 (primary key)
        in: path
        name: ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 삭제 성공
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 잘못된 상품 번호
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 권한 없음
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 삭제 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 상품 삭제
      tags:
      - products
  /products/:id/stock:
    put:
      consumes:
      - application/json
      description: 상품의 재고 수량을 수정합니다. (관리자 전용)
      parameters:
      - description: 기본키 (primary key)
        in: path
        name: ID
        required: true
        type: integer
      - description: 재고 정보
        in: body
        name: stockRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdateStockRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 수정 성공
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 잘못된 요청
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: 권한 없음
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 수정 실패
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      summary: 재고 수정
      tags:
      - products
securityDefinitions:
  Bearer:
    description: A commerce-system service API in Go using Gin framework
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
