definitions:
  usecases.HealthStatus:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Endpoint to perform a health check and verify the service status
      produces:
      - application/json
      responses:
        "200":
          description: Health check result
          schema:
            $ref: '#/definitions/usecases.HealthStatus'
      summary: Performs a health check
      tags:
      - health
swagger: "2.0"
